### ISSUE TITLE
Re: Ubuntu 18.04

### ISSUE THREAD

**Issue by dcurtisatmit** [OpenCilk/www.opencilk.org#36]
The install page says that OpenCilk works on Ubuntu 18.04... but this tgz file, maybe not unsurprisingly, doesn't work.
            [OpenCilk-1.1-LLVM-12.0.0-Ubuntu-20.04-x86_64.tar.gz]
doesn't work on Ubuntu 18.04

Invoking bin/clang gives the following error message:
bin/clang: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory

Several ways to fix this:
        1) easiest: remove Ubuntu 18.04 from the list at the top of the page
        2) add some caveat that OpenCilk for Ubuntu 18.04 needs to be built from scratch

**Comment by behoppe** [comment]
Thanks @dcurtisatmit. I was surprised, but now I see that version 1.0 had a distinct binary download for Ubuntu 18.04, which no longer exists for version 1.1. I will remove Ubuntu 18.04 from the list at the top of the page and say that you can build from source if necessary. (I guess this happened since 20.04 is now a long-term stable release?)
